# Functional Spec — {{objective_short}}

> Generated by SpecWriter at PHASE 0.2. Confirmed by user before DAG construction.
> session_id: {{session_id}}
> created_at: {{created_at}}

---

## Objective

{{objective}}

## Scope

{{scope}}

## Acceptance Criteria

{{acceptance_criteria}}

## Constraints

{{constraints}}

## Out of Scope

{{out_of_scope}}

---

## Task Decomposition

<!-- Task blocks below are parsed by sdk/core/dag.SpecDAGParser.        -->
<!-- Format: ### task::<node_id> followed by key: value lines.           -->
<!-- node_id: unique, kebab-case. depends_on: comma-separated or (none). -->
<!-- files_in_scope: comma-separated paths or (tbd). experts: int ≥ 1.   -->

{{task_decomposition}}
