# Functional Spec — {{objective_short}}

> Generated by SpecWriter at PHASE 0.2. Confirmed by user before DAG construction.
> session_id: {{session_id}}
> created_at: {{created_at}}

---

## Objective

{{objective}}

## Scope

{{scope}}

## Acceptance Criteria

{{acceptance_criteria}}

## Constraints

{{constraints}}

## Out of Scope

{{out_of_scope}}

---

## Task Decomposition

<!-- Task blocks below are parsed by sdk/core/dag.py SpecDAGParser.          -->
<!-- Format: ### task::<node_id> followed by key: value lines.                -->
<!-- node_id must be unique, snake_case or kebab-case, no spaces.             -->
<!-- depends_on: comma-separated node_ids, or "(none)" if root task.          -->
<!-- files_in_scope: comma-separated relative paths, or "(tbd)" if unknown.   -->
<!-- experts: integer ≥ 1. Use 2+ only for parallelisable subtasks.           -->

### task::{{task_1_id}}
- **domain**: {{task_1_domain}}
- **description**: {{task_1_description}}
- **depends_on**: (none)
- **files_in_scope**: {{task_1_files}}
- **experts**: 1

### task::{{task_2_id}}
- **domain**: {{task_2_domain}}
- **description**: {{task_2_description}}
- **depends_on**: {{task_1_id}}
- **files_in_scope**: {{task_2_files}}
- **experts**: 1
