"""sdk — PIV/OAC v5.0 framework engine.

Public API:
    Session    — main entry point (Session.init(...).run(...))
    Gate       — gate type and verdict constants
    Vault      — credential and injection gate
    Engram     — read-only engram access
    Tier       — execution tier constants

Usage (Mode 1 — clone):
    from sdk import Session
    Session.init(provider="anthropic").run(objective="...")

Usage (Mode 2 — pip install):
    from piv_oac import Session
    Session.init(provider="anthropic").run(objective="...")
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from sdk.core.dag import DAG, DAGBuilder, DAGNode
from sdk.core.init import InitError, Initializer
from sdk.core.interview import (
    CallbackHandler,
    ConsoleHandler,
    InterviewSession,
    PreSuppliedHandler,
)
from sdk.core.loader import FrameworkLoader
from sdk.core.session import SessionManager
from sdk.core.spec_writer import SpecWriter
from sdk.engram import EngramReader
from sdk.gates import GateEvaluator, GateType, GateVerdict
from sdk.metrics import TelemetryLogger
from sdk.providers import ProviderRouter, Tier
from sdk.providers.anthropic import AnthropicProvider
from sdk.providers.ollama import OllamaProvider
try:
    from sdk.providers.openai import OpenAIProvider
except ImportError:
    OpenAIProvider = None  # type: ignore[assignment,misc]
from sdk.utils.complexity import ComplexityClassifier
from sdk.vault import Vault

# Re-export for public API convenience
Gate   = GateType
Engram = EngramReader

__version__ = "5.0.0"
__all__ = [
    "Session",
    "Gate",
    "GateVerdict",
    "Vault",
    "Engram",
    "Tier",
    "DAG",
    "DAGBuilder",
    "DAGNode",
    "FrameworkLoader",
    "SessionManager",
    "TelemetryLogger",
    "ComplexityClassifier",
]


class Session:
    """Top-level session builder. Entry point for all PIV/OAC interactions.

    Usage:
        Session.init(provider="anthropic").run(objective="add JWT auth")
        Session.init(provider="anthropic", local_model="llama3.2:1b").run(...)
        Session.init(provider="ollama", model="llama3.2:3b").run(...)

    See _context_.md §8 for Session.init() parameter reference.
    """

    def __init__(
        self,
        provider: str,
        model: str | None = None,
        local_model: str | None = None,
        repo_root: Path | None = None,
    ) -> None:
        self._provider_name  = provider
        self._model          = model
        self._local_model    = local_model
        self._repo_root      = repo_root or Path.cwd()
        self._cloud_provider = None
        self._local_provider = None
        self._router         = None
        self._session_mgr    = None
        self._telemetry      = None

    @classmethod
    def init(
        cls,
        provider: str,
        model: str | None = None,
        local_model: str | None = None,
        repo_root: Path | None = None,
    ) -> "Session":
        """Configure and return a Session instance (does not start execution).

        Args:
            provider:    Cloud provider name ("anthropic", "openai", "ollama").
            model:       Override default model for the cloud provider.
            local_model: Ollama model tag for Tier 2 (e.g. "llama3.2:1b").
            repo_root:   Repository root (defaults to cwd).
        """
        return cls(
            provider=provider,
            model=model,
            local_model=local_model,
            repo_root=repo_root,
        )

    def run(
        self,
        objective: str,
        answers: dict | None = None,
        on_question=None,
    ) -> dict[str, Any]:
        """Execute the full PIV/OAC session for *objective*.

        Args:
            objective:   The user's goal in natural language.
            answers:     Pre-supplied answers dict (programmatic mode).
            on_question: Callback for custom UI (receives question, returns answer str).

        Returns:
            Session result dict with session_id, status, and summary.
        """
        self._bootstrap()

        # PHASE 0: injection scan
        Vault.scan_for_injection(objective)

        # Complexity classification (Tier 1)
        classification = ComplexityClassifier.classify(objective)

        # PHASE 0.1: interview (Level 2 only)
        transcript: list[dict] = []
        if not classification.fast_track:
            handler = self._build_handler(answers, on_question)
            interview = InterviewSession(handler)
            # Questions are generated by the Orchestrator agent at runtime.
            # Here we stub the hook — orchestrator fills this during actual execution.
            transcript = interview.transcript

        # Create session state
        state = self._session_mgr.create(  # type: ignore[union-attr]
            objective=objective,
            provider=self._provider_name,
        )
        session_id = state["session_id"]

        self._telemetry = TelemetryLogger(  # type: ignore[assignment]
            session_id=session_id,
            log_dir=self._repo_root / "logs",
        )

        self._telemetry.record({
            "level": "INFO",
            "session_id": session_id,
            "agent_id": "Session",
            "phase": "PHASE_0",
            "action": "session_start",
            "outcome": "OK",
            "tier": 1,
            "duration_ms": 0,
            "tokens_used": 0,
            "detail": {
                "complexity_level": classification.level,
                "fast_track": classification.fast_track,
                "reason": classification.reason,
            },
        })

        return {
            "session_id": session_id,
            "status": "active",
            "complexity": classification.level,
            "fast_track": classification.fast_track,
        }

    # ------------------------------------------------------------------
    # Internal
    # ------------------------------------------------------------------

    def _bootstrap(self) -> None:
        """Instantiate providers, router, and session manager."""
        # Cloud provider
        if self._provider_name == "anthropic":
            self._cloud_provider = AnthropicProvider(model=self._model or "claude-sonnet-4-6")
        elif self._provider_name == "openai":
            self._cloud_provider = OpenAIProvider(model=self._model or "gpt-4o")
        elif self._provider_name == "ollama":
            self._cloud_provider = None  # fully local session
        else:
            raise ValueError(f"Unknown provider: '{self._provider_name}'")

        # Local provider (Tier 2)
        if self._local_model:
            self._local_provider = OllamaProvider(model=self._local_model)

        self._router = ProviderRouter(
            cloud_provider=self._cloud_provider,
            local_provider=self._local_provider,
        )
        self._session_mgr = SessionManager(repo_root=self._repo_root)

    @staticmethod
    def _build_handler(answers: dict | None, on_question) -> Any:
        if answers is not None:
            return PreSuppliedHandler(answers)
        if on_question is not None:
            return CallbackHandler(on_question)
        return ConsoleHandler()
